In [1]:
import pandas as pd
import json

In [2]:
df = pd.read_json("extracted_conclusions/agg_df.json")

In [3]:
parsed_dilemmas = json.load(open("ApproxDilemmasSegmentLocation.json", "r"))

In [4]:
df

,output,acceptable,not_acceptable,filename,dilemma
0,"{\n ""acceptable"": [\n ""Tal med din s...",[Tal med din søster Josefine ansigt til ansigt...,[At Emma eller familien optræder som dommer og...,2023-03-04-loerdag-4-mar-2023-15452348009.json,Emmas søster Josefine skal snart giftes med Pe...
1,"{\n ""acceptable"": [\n ""At den kommen...",[At den kommende mand sætter sig ned med sin m...,[At lade Line tage snakken med svigermoren; de...,2022-01-15-loerdag-15-jan-2022-11032200002.json,Cecilie er i tvivl om hun af hensyn til sit ba...
2,"{\n ""acceptable"": [\n ""Vær ærlig og ...","[Vær ærlig og sig det til ham — fortæl manden,...",[At holde mund og lade være med at sige noget ...,2021-10-16-loerdag-16-okt-2021-11032112541.json,Mia arbejder hos en tandlæge og har mødt sin d...
3,"{\n ""acceptable"": [\n ""Ringe til far...","[Ringe til farfaren nu, hvor I har hans telefo...",[Sende endnu et brev til farfaren (ikke sende ...,2018-11-03-mads-og-monopolet-14981812644.json,"Britta og Jeanette har mistet deres far, og de..."
4,"{\n ""acceptable"": [\n ""Banke på og s...","[Banke på og sige hej, og spørge, om hun har l...",[Sætte et skilt i vinduet med teksten 'har du ...,2020-11-28-mads-og-monopolet-14982012648.json,"Sisse har en genbo, der virker ensom, og hun e..."
...,...,...,...,...,...
3448,"{\n ""acceptable"": [\n ""Lav en 'klamh...",[Lav en 'klamhedstest' for dig selv: mærk efte...,[At bryde op straks udelukkende på grund af po...,2022-10-29-loerdag-29-okt-2022-11032200038.json,"Emma har datet Johnny i nogle måneder, men und..."
3449,"{\n ""acceptable"": [\n ""Tag en ærlig,...","[Tag en ærlig, konkret samtale med Mads: sig, ...",[Tvinge eller presse Mads til at ville børn el...,2023-05-20-loerdag-20-maj-2023-15452348020.json,"Nikolaj synes, at plateausko er turnoff, men h..."
3450,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2023-09-23-loerdag-23-sep-2023-15452348038.json,"Matilde er i tvivl, om hun bør aflevere en hal..."
3451,"{\n ""acceptable"": [\n ""Lev med det —...",[Lev med det — accepter at børnelarm er en del...,[Gå i gang med en stor diskussion eller konfro...,2024-05-25-loerdag-25-maj-2024-15452448022.json,"Mathilde er ikke en som normalt hader børn, me..."
3452,"{\n ""acceptable"": [\n ""Tag den lange...",[Tag den lange cykeltur til lavkagehuset for a...,[],2020-03-28-mads-og-monopolet-14982012613.json,Emma er frivillig indkøber for en ældre kvinde...

In [5]:
df.iloc[0]["output"]

'{\n    "acceptable": [\n        "Tal med din søster Josefine ansigt til ansigt (helst inden invitationerne sendes): sig at du er bekymret, spørg interesseret ind til, om hun har det godt, undgå at konkludere eller dømme, og lad hende tage beslutningen.",\n        "Fortæl Josefine faktuelt, hvad Peter advarede dig om (fx at han sagde, at fundamentet ikke føles som det skal være), men gør det uden anbefalinger eller pres — del viden og spørg hvordan hun har det.",\n        "Tag en samtale med Peter face-to-face: sig at den samtale han havde med dig gjorde dig ubehageligt til mode, og bed ham om at tale med Josefine eller tage stilling til, om han vil gifte sig."\n    ],\n    "not-acceptable": [\n        "At Emma eller familien optræder som dommer og direkte fortæller Josefine, at \'han er ikke den rigtige\' eller anbefaler, at hun skal droppe brylluppet.",\n        "At Emma holder informationen for sig selv og ikke siger noget overhovedet (ingen handling)."\n    ]\n}'

In [6]:
df["len_acc"] = df["acceptable"].apply(lambda x: len(x))

In [7]:
issues_df = df[df["len_acc"] == 0]

In [8]:
issues_df

,output,acceptable,not_acceptable,filename,dilemma,len_acc
17,"{""acceptable"": [], ""not-acceptable"": []}",[],[],2023-07-01-loerdag-1-jul-2023-15452348026.json,"Mia spørger Monopolet, hvad hun skal gøre, da ...",0
28,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2024-04-20-loerdag-20-apr-2024-15452448017.json,Marta gør meget ud af morgenbordet til fødsels...,0
34,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2024-12-07-loerdag-7-dec-2024-15452448050.json,"Agnes er generet af at hendes nabo, Dennis, ry...",0
36,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2021-03-13-loerdag-13-mar-2021-11032112510.json,Sonja ønsker sig inderligt at få et barn mere ...,0
69,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2024-02-03-loerdag-3-feb-2024-15452448005.json,"Kasper er i tvivl om, hvad han skal stille op ...",0
...,...,...,...,...,...,...
3423,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2020-04-04-mads-og-monopolet-14982012614.json,"Martha er i tvivl, om hun kan hente 6 flasker ...",0
3426,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2018-10-20-mads-og-monopolet-14981812642.json,Signes kristne familie vil ikke acceptere hend...,0
3432,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2017-11-18-mads-og-monopolet-uge-46-1498171264...,"Linnea skal besøge en fyr i Colombia, men nu e...",0
3442,"{""acceptable"": [], ""not-acceptable"": []}",[],[],2018-09-22-mads-og-monopolet-14981812638.json,"Mia har en kæreste, der bor i Belgien, som vil...",0
3450,"{\n ""acceptable"": [],\n ""not-acceptable""...",[],[],2023-09-23-loerdag-23-sep-2023-15452348038.json,"Matilde er i tvivl, om hun bør aflevere en hal...",0

In [9]:
for _, row in issues_df.iterrows():
    print(row["filename"])
    print(row["dilemma"])
    print(parsed_dilemmas[row["filename"]][row["dilemma"]]["selected"])
    print("-"*15)

2023-07-01-loerdag-1-jul-2023-15452348026.json
Mia spørger Monopolet, hvad hun skal gøre, da hendes gangbesværede far over 80 år drømmer om en ferie med Mia og hendes aktive børn i Sydspanien.
{'start': 1670, 'end': 1674, 'similarity': 0.4702383279800415}
---------------
2024-04-20-loerdag-20-apr-2024-15452448017.json
Marta gør meget ud af morgenbordet til fødselsdage, men hun synes ikke, at hendes venner lever op til samme standard, når Marta selv har fødselsdag.
{'start': 1677, 'end': 1686, 'similarity': 0.4420267939567566}
---------------
2024-12-07-loerdag-7-dec-2024-15452448050.json
Agnes er generet af at hendes nabo, Dennis, ryger hash fem gange om dagen og hoster og hakker på alle tider af døgnet.
{'start': 49, 'end': 51, 'similarity': 0.3048720359802246}
---------------
2021-03-13-loerdag-13-mar-2021-11032112510.json
Sonja ønsker sig inderligt at få et barn mere og overvejer at få fjernet sin spiral uden at fortælle det til sin mand.
{'start': 609, 'end': 611, 'similarity': 0.5960884094238281}
---------------
2024-02-03-loerdag-3-feb-2024-15452448005.json
Kasper er i tvivl om, hvad han skal stille op med sin morfar og sin mors kæreste Lars, der har et anspændt forhold til hinanden.
{'start': 1021, 'end': 1027, 'similarity': 0.5068554878234863}
---------------
2018-11-24-mads-og-monopolet-14981812647.json
Dorte og Leif vil gerne vide, om man som chef skal gå tidligt hjem fra julefrokosten
{'start': 5, 'end': 7, 'similarity': 0.41081899404525757}
---------------
2020-02-29-mads-og-monopolet-14982012609.json
Sonja og de andre kvinder i kageklubben vil gerne have et medlem, Bente, ud af kageklubben, fordi hun sladrer.
{'start': 132, 'end': 134, 'similarity': 0.2936572730541229}
---------------
2019-10-05-mads-og-monopolet-14981912640.json
Theas far på 50 har fået en kæreste på 25.
{'start': 189, 'end': 191, 'similarity': 0.3164416551589966}
---------------
2021-05-15-loerdag-15-maj-2021-11032112519.json
Gurlis kæreste har to hjemmeboende drenge, der ikke har faste pligter i hjemmet.
{'start': 1555, 'end': 1561, 'similarity': 0.42882952094078064}
---------------
2023-04-22-loerdag-22-apr-2023-15452348016.json
Diana frygter, at hun allerede er ved at gå en fremtid som husmor i møde, da hendes kæreste Jonas ikke hjælper til med de huslige pligter.
{'start': 487, 'end': 491, 'similarity': 0.5174065828323364}
---------------
2018-08-25-mads-og-monopolet-14981812634.json
Nina er klasselærer og ved ikke, om hun skal gribe ind overfor sine tidligere elever, som holder to af klassekammeraterne udenfor på Facebook.
{'start': 751, 'end': 753, 'similarity': 0.6905263662338257}
---------------
2022-02-19-loerdag-19-feb-2022-11032200007.json
Suzans mand bruger meget tid på sin mobiltelefon, når familien er samlet.
{'start': 215, 'end': 222, 'similarity': 0.45418524742126465}
---------------
2022-06-04-loerdag-4-jun-2022-11032200022.json
Julia har svært ved at tænde på John, der tror at han er sexet, hvis blot han er nøgen, og som samtidigt har for meget hår på kroppen til Julias smag.
{'start': 795, 'end': 797, 'similarity': 0.6301208734512329}
---------------
2021-05-08-loerdag-8-maj-2021-11032112518.json
Charlotte og Kenneth har en meget anmassende australsk nabo.
{'start': 529, 'end': 531, 'similarity': 0.4379526376724243}
---------------
2019-03-23-mads-og-monopolet-14981912612.json
Rosa er officer og vil gerne udsendes, men hun vil også gerne have et barn.
{'start': 87, 'end': 90, 'similarity': 0.46233123540878296}
---------------
2020-10-10-mads-og-monopolet-14982012641.json
Lars er frustreret over, at hans søster og svoger kun ønsker sig pengegaver
{'start': 209, 'end': 211, 'similarity': 0.5257490873336792}
---------------
2022-04-16-loerdag-16-apr-2022-11032200015.json
Jens fik sidste år konstateret parkinsons sygdom og er i tvivl om, hvornår og hvordan han fortæller om sin sygdom til potentielle dates.
{'start': 64, 'end': 66, 'similarity': 0.3513219952583313}
---------------
2021-06-26-loerdag-26-jun-2021-11032112525.json
Jonathan skal på barsel og vil gerne være en del af mødregruppen, men ikke alle i mødregruppen er vilde med den ide.
{'start': 205, 'end': 207, 'similarity': 0.5783324837684631}
---------------
2023-11-18-loerdag-18-nov-2023-15452348046.json
Julies kæreste Morten klipper ikke sine tånegle, og når Morten tager sokkerne af, kan Julie ikke tænke på andet.
{'start': 60, 'end': 62, 'similarity': 0.4085625410079956}
---------------
2022-02-12-loerdag-12-feb-2022-11032200006.json
Mille har fået foretaget en brystforstørrende operation, og er i tvivl om hvorvidt hun skal fortælle sin far om operationen.
{'start': 1159, 'end': 1167, 'similarity': 0.48496654629707336}
---------------
2023-02-18-loerdag-18-feb-2023-15452348007.json
Rikke har aldrig mødt sin kæreste Thomas' familie og føler, at Thomas vil holde hende hemmelig for offentligheden.
{'start': 13, 'end': 15, 'similarity': 0.2499658763408661}
---------------
2023-02-18-loerdag-18-feb-2023-15452348007.json
Line og Bo vil gerne flytte sammen, men Line ønsker sig en minimalistisk indretningsstil mens Bo omvendt samler på nips, plakater, dvd'er og whiskyflasker.
{'start': 10, 'end': 12, 'similarity': 0.19250132143497467}
---------------
2024-03-30-loerdag-30-mar-2024-15452448014.json
Den fortvivlede romantiker Rasmus spørger Monopolet, om han kan tillade sig at række ud til Emma, som han gav et lift til Aarhus.
{'start': 121, 'end': 123, 'similarity': 0.4702138900756836}
---------------
2019-05-18-mads-og-monopolet-14981912620.json
Mille arbejder i en bager og oplever, at kunderne er ekstremt uhøflige.
{'start': 25, 'end': 28, 'similarity': 0.3713117241859436}
---------------
2021-01-16-loerdag-16-jan-2021-11032112502.json
Klaras veninde lugter af sved.
{'start': 96, 'end': 98, 'similarity': 0.3274734616279602}
---------------
2017-02-11-mads-og-monopolet-uge-6-14981712606.json
Stine er træt af, at hendes veninder er begyndt at tage traditionen Babyshower til sig.
{'start': 175, 'end': 177, 'similarity': 0.5294919013977051}
---------------
2021-01-23-loerdag-23-jan-2021-11032112503.json
Klara dater en konspirationsteoretiker.
{'start': 3, 'end': 5, 'similarity': 0.478356271982193}
---------------
2016-09-24-mads-og-monopolet-uge-38-2016-14981612638.json
Anna er træt af at trække arbejdslæsset i gymnasiet.
{'start': 1064, 'end': 1070, 'similarity': 0.42464137077331543}
---------------
2025-02-01-loerdag-1-feb-2025-15452547004.json
Sofie er bekymret for sin kæreste Felix's kontakt med hans ekskæreste Anna, som Felix dyrker taekwondo med.
{'start': 684, 'end': 686, 'similarity': 0.5771615505218506}
---------------
2020-02-15-mads-og-monopolet-14982012607.json
Cille ser en fyr, der konsekvent lader hende betale regningen, når de er ude at spise.
{'start': 115, 'end': 118, 'similarity': 0.5046563148498535}
---------------
2022-10-08-loerdag-8-okt-2022-11032200035.json
Mads er studentermedhjælper i en virksomhed, hvor en af hans kollegaer dagligt falder i søvn på sin kontorplads.
{'start': 198, 'end': 210, 'similarity': 0.46414822340011597}
---------------
2018-08-11-mads-og-monopolet-14981812632.json
Mette og hendes kæreste bor sammen men kan ikke blive enige om, hvordan de fordeler de fælles huslige pligter.
{'start': 157, 'end': 159, 'similarity': 0.41600197553634644}
---------------
2019-08-10-mads-og-monopolet-paa-smukfest-14981912632.json
Tina er 26 og har siden hun var 19 været sammen med 16 fyre. Hun er bekymret for, om hendes nye kæreste vil synes, hun er promiskuøs.
{'start': 324, 'end': 326, 'similarity': 0.46070021390914917}
---------------
2017-08-12-mads-og-monopolet-paa-smukfest-14981712632.json
Katja og Siljes veninde bliver ved at gå tilbage til en fyr, der konstant er hende utro
{'start': 282, 'end': 286, 'similarity': 0.6250629425048828}
---------------
2016-12-10-mads-og-monopolet-uge-49-2016-14981612649.json
Lines bror og kæreste deler ex
{'start': 492, 'end': 494, 'similarity': 0.5154273509979248}
---------------
2023-11-25-loerdag-25-nov-2023-15452348047.json
Rikke er en del af et slæng med gode venner, men Rikke får præstationsangst hver gang hun skal lægge hus til, da veninden Lisa går mere op i rengøring end de fleste.
{'start': 167, 'end': 169, 'similarity': 0.660612940788269}
---------------
2024-11-02-loerdag-2-nov-2024-15452448045.json
Pelle spørger Monopolet om han kan tillade sig ikke at invitere sine venners kærester med til sit bryllup, da han kun har mødt kæresterne få gange.
{'start': 353, 'end': 356, 'similarity': 0.48333740234375}
---------------
2024-02-03-loerdag-3-feb-2024-15452448005.json
Kaya, Emilie og Catrine er irriteret over Cornelius, som de bor i kollektiv med, da han blandt andet konstant tager pull-ups i loftsbjælkerne - i bar mave - i deres fælles stue.
{'start': 2005, 'end': 2010, 'similarity': 0.46474331617355347}
---------------
2016-10-15-mads-og-monopolet-uge-41-2016-14981612641.json
Jonas dater en 10 år ældre kvinde, der ikke vil have flere børn
{'start': 272, 'end': 274, 'similarity': 0.6712638139724731}
---------------
2019-12-07-mads-og-monopolet-14981912649.json
Nina går op i økologi, men hendes forældre insisterer på at købe konventionelt kød og tilbehør til juleaften.
{'start': 128, 'end': 130, 'similarity': 0.4339110255241394}
---------------
2022-09-03-loerdag-3-sep-2022-11032200030.json
Kasper og Anna har udset sig et vennepar, som de ønsker at have sex med, og spørger Monopolet, hvordan man indleder den samtale med sine venner.
{'start': 218, 'end': 222, 'similarity': 0.4578237533569336}
---------------
2024-02-03-loerdag-3-feb-2024-15452448005.json
Esther deler vaskekælder med 20 andre lejligheder og er nu havnet i en twist om tørrestativerne.
{'start': 71, 'end': 73, 'similarity': 0.4345752000808716}
---------------
2017-01-07-mads-og-monopolet-uge-1-14981712601.json
Majken er i tvivl om hvornår hun skal fortælle dates at hun lider af inkontinens.
{'start': 631, 'end': 636, 'similarity': 0.4620775580406189}
---------------
2023-02-04-loerdag-4-feb-2023-15452348005.json
Emmas mor har efter Emmas fars død fundet en ny kæreste, men selvom kæresten ingenting forkert har gjort, har Emma stadig svært ved at acceptere ham i familien.
{'start': 2732, 'end': 2738, 'similarity': 0.7441137433052063}
---------------
2017-04-01-mads-og-monopolet-uge-13-14981712613.json
Bente har fået sin afdøde venindes dagbøger og er i tvivl, om hun skal læse dem.
{'start': 465, 'end': 468, 'similarity': 0.6796312928199768}
---------------
2022-01-29-loerdag-29-jan-2022-11032200004.json
Vibeke og hendes mand har for nyligt fundet et nyt potentielt vennepar, men Vibeke irriteres over, at den ene afbryder meget i samtalerne.
{'start': 119, 'end': 121, 'similarity': 0.47310417890548706}
---------------
2019-02-23-mads-og-monopolet-14981912608.json
Martin vil gerne være sæddonor, men hans kæreste er imod.
{'start': 1592, 'end': 1597, 'similarity': 0.487868070602417}
---------------
2017-05-20-mads-og-monopolet-uge-20-14981712620.json
Dilemma 3. Simone og Troels får altid rollerne som dem der skal underholde til bryllupper.
{'start': 117, 'end': 119, 'similarity': 0.3900156617164612}
---------------
2019-03-23-mads-og-monopolet-14981912612.json
Malene har en halvbror, som hun aldrig har haft kontakt til.
{'start': 74, 'end': 76, 'similarity': 0.5388250946998596}
---------------
2023-02-18-loerdag-18-feb-2023-15452348007.json
Jørgen har to teenagedrenge der "sumper", og det skaber problemer i Jørgens forhold til sin kæreste Helle.
{'start': 2, 'end': 4, 'similarity': 0.25258952379226685}
---------------
2020-09-12-mads-og-monopolet-14982012637.json
Ditte er ked af, at hendes kæreste har fotos liggende på sin computer fra tidligere forhold
{'start': 1043, 'end': 1048, 'similarity': 0.5187368988990784}
---------------
2020-02-08-mads-og-monopolet-14982012606.json
Niels ekskone har frabedt sig, at han giver deres barn en rejse i konfirmationsgave.
{'start': 304, 'end': 306, 'similarity': 0.4484456777572632}
---------------
2019-08-10-mads-og-monopolet-paa-smukfest-14981912632.json
Marina og Anne er frustrerede over, at deres naboer i teltlejren på Smukfest spiller dødsmetal kl. 6 om morgenen.
{'start': 101, 'end': 103, 'similarity': 0.3951210677623749}
---------------
2025-06-21-loerdag-21-jun-2025-15452547024.json
Lene spørger Monopolet, om hun kan tillade sig at tage 4 timer væk fra hjemmet og høre heavy-metal for en aften, selvom hendes datter Luna ikke vil puttes af andre.
{'start': 3096, 'end': 3104, 'similarity': 0.570648193359375}
---------------
2021-04-17-loerdag-17-apr-2021-11032112515.json
Sidsels veninde er meget ivrig sælger af brugt børnetøj.
{'start': 526, 'end': 531, 'similarity': 0.6169013977050781}
---------------
2021-08-28-loerdag-28-aug-2021-11032112534.json
Brian er blevet ansat i et vikarjob, som han er rigtig glad for, men nu er han pludselig blevet kaldt til samtale på sit drømmejob.
{'start': 22, 'end': 24, 'similarity': 0.4683094024658203}
---------------
2023-04-15-loerdag-15-apr-2023-15452348015.json
Johannas kæreste Karl får svedige håndflader og flakkende blik, når snakken falder på at flytte sammen.
{'start': 147, 'end': 151, 'similarity': 0.503925621509552}
---------------
2020-02-29-mads-og-monopolet-14982012609.json
Clara mødes med en fyr på hotel og har sex. Hun lagde ud sidste gang, men er i tvivl om hun kan bede ham om at overføre beløbet.
{'start': 131, 'end': 133, 'similarity': 0.37483465671539307}
---------------
2019-03-30-mads-og-monopolet-14981912613.json
Berit har tidligere sugerdated og er nu i tvivl om hun skal fortælle det til sin kæreste.
{'start': 183, 'end': 185, 'similarity': 0.520844578742981}
---------------
2024-09-14-loerdag-14-sep-2024-15452448038.json
Torben har ikke haft kontakt til sin søn Patrick i 8 år og er nu i tvivl, om han skal skrive Patrick ud af sit testamente.
{'start': 735, 'end': 746, 'similarity': 0.6170202493667603}
---------------
2020-12-12-mads-og-monopolet-14982012650.json
Anders vil gerne købe julegaver til unge hjemløse for de penge, han får af sine forældre til jul.
{'start': 2042, 'end': 2051, 'similarity': 0.5004254579544067}
---------------
2023-03-25-loerdag-25-mar-2023-15452348012.json
Søren og hans kæreste Line venter deres første barn, men Søren og Line står begge stejlt på, at barnet bør hedde deres respektive efternavne.
{'start': 243, 'end': 247, 'similarity': 0.5137974619865417}
---------------
2019-11-16-mads-og-monopolet-14981912646.json
Elisabeth oplever at folk forstyrrer hendes koncertoplevelser ved at sidde og filme konstant.
{'start': 1861, 'end': 1870, 'similarity': 0.5452965497970581}
---------------
2023-11-11-loerdag-11-nov-2023-15452348045.json
Erika er gift med Troels, der har teenagedatteren Liva fra et tidligere forhold, og Erika er i tvivl om, hvordan hun bedst håndterer Liva, der har det svært.
{'start': 1843, 'end': 1848, 'similarity': 0.6058101654052734}
---------------
2018-09-22-mads-og-monopolet-14981812638.json
Kamille opdagede for mange år siden en hed korrespondance mellem sin far og en anden kvinde, som hun ikke har delt med nogen.
{'start': 133, 'end': 135, 'similarity': 0.5058473348617554}
---------------
2022-12-24-jul-med-sara-og-monopolet-11032200046.json
Karsten tjener ikke lige så meget som sin kone Yvonne, og det har Yvonne svært ved at forlige sig med.
{'start': 897, 'end': 900, 'similarity': 0.5537645816802979}
---------------
2017-10-28-mads-og-monopolet-uge-43-14981712643.json
Andrea, Cecilie og Mille har en nabo, der belurer dem.
{'start': 128, 'end': 130, 'similarity': 0.38887304067611694}
---------------
2025-02-01-loerdag-1-feb-2025-15452547004.json
Rikke spørger monopolet, om hun skal lege Kirsten Giftekniv og hjælpe sin veninde Berit, der ikke kan finde kærligheden.
{'start': 291, 'end': 293, 'similarity': 0.6118287444114685}
---------------
2024-02-24-loerdag-24-feb-2024-15452448009.json
Laura synes, det er irriterende, at kassedamen i hendes lokale supermarked kommenterer på hendes indkøb.
{'start': 124, 'end': 126, 'similarity': 0.6146480441093445}
---------------
2017-05-06-mads-og-monopolet-uge-18-14981712618.json
Anja hjalp i sidste uge en fuld mand, der væltede på cykel. Han indrømmede, at han er alkoholiker, og hun overvejer nu at hjælpe ham.
{'start': 155, 'end': 157, 'similarity': 0.3872782588005066}
---------------
2020-05-30-mads-og-monopolet-14982012622.json
Trine har lavet en halvnøgen kalender, som nu er i hendes ekskærestes varetægt.
{'start': 265, 'end': 267, 'similarity': 0.5483426451683044}
---------------
2017-09-23-mads-og-monopolet-uge-38-14981712638.json
Mie bor med sin bedste ven, og nu er de også blevet bollevenner.
{'start': 852, 'end': 856, 'similarity': 0.46535664796829224}
---------------
2022-11-26-loerdag-26-nov-2022-11032200042.json
Williams kæreste Rikke bruger sin telefon meget, når hun kører bil, og William er i tvivl, om hvordan han skal gribe situationen an.
{'start': 366, 'end': 373, 'similarity': 0.41119036078453064}
---------------
2020-01-11-mads-og-monopolet-14982012602.json
Emilie er i tvivl, om hun skal have sin søsters bonusbørn med på et familiefoto.
{'start': 190, 'end': 192, 'similarity': 0.48702478408813477}
---------------
2024-12-14-loerdag-14-dec-2024-15452448051.json
Nikolaj og hans kæreste skal i parterapi, men Nikolaj har en hukommelse som en si og har derfor foreslået at optage samtalerne.
{'start': 525, 'end': 527, 'similarity': 0.42402106523513794}
---------------
2024-01-27-loerdag-27-jan-2024-15452448004.json
Kasper og hans kæreste er dybt uenige om, hvorvidt de skal have en mikroovn i hjemmet eller ej.
{'start': 132, 'end': 134, 'similarity': 0.5393631458282471}
---------------
2023-11-18-loerdag-18-nov-2023-15452348046.json
Katrine er mor til en teenagesøn, som ifølge Katrine "onanerer helt vildt meget".
{'start': 620, 'end': 634, 'similarity': 0.46415504813194275}
---------------
2020-11-14-mads-og-monopolet-14982012646.json
Berit gider ikke være med i pakkekalenderlegen på sit job.
{'start': 422, 'end': 424, 'similarity': 0.4674129784107208}
---------------
2025-02-08-loerdag-8-feb-2025-15452547005.json
Jesper er ved at blive vanvittig over sin kærestes nye, uopdragne hund.
{'start': 544, 'end': 550, 'similarity': 0.5364469885826111}
---------------
2020-04-11-mads-og-monopolet-14982012615.json
Dea er frustreret over, at hendes veninder giver oplevelsesgaver, som aldrig bliver realiseret.
{'start': 117, 'end': 123, 'similarity': 0.49596524238586426}
---------------
2022-01-15-loerdag-15-jan-2022-11032200002.json
Helle er kommet til skade under sex og er i tvivl om hun kan bede sin sexpartner betale halvdelen af tandlægeregningen.
{'start': 406, 'end': 410, 'similarity': 0.44492557644844055}
---------------
2017-05-27-mads-og-monopolet-uge-21-14981712621.json
Søs er træt af sin mands overforbrug af hans smartphone
{'start': 165, 'end': 167, 'similarity': 0.5094910860061646}
---------------
2020-01-25-mads-og-monopolet-14982012604.json
Rikke har barn med en australier, men hun længes efter Danmark.
{'start': 122, 'end': 125, 'similarity': 0.6073364019393921}
---------------
2016-11-19-mads-og-monopolet-uge-46-2016-14981612646.json
Noras kæreste vil ikke flytte sammen.
{'start': 381, 'end': 383, 'similarity': 0.5926017165184021}
---------------
2025-09-20-loerdag-20-sep-2025-15452547032.json
Signe har skrevet et brev om sin barndom, og nu er hun i tvivl, om hun skal give brevet til sin far, hvis hårde opdragelse har påvirket Signe meget.
{'start': 808, 'end': 810, 'similarity': 0.6445593237876892}
---------------
2021-11-13-loerdag-13-nov-2021-11032112545.json
Søren plejer at holde jul med sin ekskone og deres fælles børn, men nu har Søren fået en ny kæreste.
{'start': 1719, 'end': 1730, 'similarity': 0.5152936577796936}
---------------
2019-08-10-mads-og-monopolet-paa-smukfest-14981912632.json
Sisse er i starten af 40'erne og er forelsket i en kvinde, der er 20 år yngre.
{'start': 324, 'end': 326, 'similarity': 0.46070021390914917}
---------------
2023-09-30-loerdag-30-sep-2023-15452348039.json

In [10]:
no_issue_df = df[df["len_acc"] > 0]

In [11]:
no_issue_df.shape

(3141, 6)

In [12]:
def viz_random_sample(df):
    sample = df.sample(1).iloc[0]
    for k in ["filename", "dilemma", "acceptable", "not_acceptable"]:
        v = sample[k]
        print(f"{k}: {v}")
        print("-"*15)

    print(parsed_dilemmas[sample["filename"]][sample["dilemma"]]["selected"])

In [13]:
viz_random_sample(no_issue_df)

filename: 2022-11-19-loerdag-19-nov-2022-11032200041.json
---------------
dilemma: Adams kæreste Robin er afhængig af regneark og bruger flere timer hver aften på at lave beregninger på sin bærbare computer.
---------------
acceptable: ['Tag hen og snak med ham ansigt til ansigt: spørg hvad der foregår, inviter til kaffe og kringle, og fortæl hvordan det påvirker dig, så I kan finde en fælles løsning.', 'Start med at finde ud af, hvad der egentlig foregår i hans lejlighed bag den lukkede dør, før du stiller krav eller laver ultimatum.', 'Spørg ham, om han selv har et bud på en løsning (lad ham komme med forslag).', 'Brug en støjmåler/et Apple Watch med dB-advarsel: giv ham eller få ham til at bruge et Apple Watch, der vibrerer eller advarer, når støjniveauet bliver for højt.', 'Lydisoler dit sted (fx plastre de mest støjfølsomme flader med æggebakker) for at dæmpe støjen.']
---------------
not_acceptable: ['Komme med krav eller ultimatum, før du ved, hvad konflikten handler om.', 'Antage eller beskylde ham for noget (fx Tourette eller andre årsager) uden først at have talt med ham og hørt hans forklaring.']
---------------
{'start': 1592, 'end': 1600, 'similarity': 0.4304116368293762}

In [42]:
no_issue_df.to_json("extracted_conclusions/agg_df_filtered.json")